// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1ovWDbplstyOCpQ9F7XIQYM12TgLXAo',
    appId: '1:667489878375:web:0ab31efb7155fe35bd6fc2',
    messagingSenderId: '667489878375',
    projectId: 'echoepic-af2b1',
    authDomain: 'echoepic-af2b1.firebaseapp.com',
    storageBucket: 'echoepic-af2b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK54ScdK51hkqNKCQQzsqOi9hp_t2voR4',
    appId: '1:667489878375:android:e1f03e2e1a77432abd6fc2',
    messagingSenderId: '667489878375',
    projectId: 'echoepic-af2b1',
    storageBucket: 'echoepic-af2b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBbWknMDJqZz1fwjmC6h6qq0oIrXwZ3jY',
    appId: '1:667489878375:ios:284c37299bdbf83fbd6fc2',
    messagingSenderId: '667489878375',
    projectId: 'echoepic-af2b1',
    storageBucket: 'echoepic-af2b1.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBbWknMDJqZz1fwjmC6h6qq0oIrXwZ3jY',
    appId: '1:667489878375:ios:284c37299bdbf83fbd6fc2',
    messagingSenderId: '667489878375',
    projectId: 'echoepic-af2b1',
    storageBucket: 'echoepic-af2b1.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );
}
